// <auto-generated />
using System;
using IlliaUlianych_APB_TZ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IlliaUlianych_APB_TZ.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("BookingRoomService", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedServicesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookingId", "SelectedServicesId");

                    b.HasIndex("SelectedServicesId");

                    b.ToTable("BookingServices", (string)null);
                });

            modelBuilder.Entity("ConferenceRoomRoomService", b =>
                {
                    b.Property<int>("AvailableServicesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConferenceRoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AvailableServicesId", "ConferenceRoomId");

                    b.HasIndex("ConferenceRoomId");

                    b.ToTable("ConferenceRoomServices", (string)null);
                });

            modelBuilder.Entity("IlliaUlianych_APB_TZ.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("IlliaUlianych_APB_TZ.Entities.ConferenceRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseHourPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConferenceRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseHourPrice = 2000m,
                            Capacity = 50,
                            Name = "Room A"
                        },
                        new
                        {
                            Id = 2,
                            BaseHourPrice = 3500m,
                            Capacity = 100,
                            Name = "Room B"
                        },
                        new
                        {
                            Id = 3,
                            BaseHourPrice = 1500m,
                            Capacity = 30,
                            Name = "Room C"
                        });
                });

            modelBuilder.Entity("IlliaUlianych_APB_TZ.Entities.RoomService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoomServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Projector",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wi-Fi",
                            Price = 300m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sound",
                            Price = 700m
                        });
                });

            modelBuilder.Entity("BookingRoomService", b =>
                {
                    b.HasOne("IlliaUlianych_APB_TZ.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IlliaUlianych_APB_TZ.Entities.RoomService", null)
                        .WithMany()
                        .HasForeignKey("SelectedServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConferenceRoomRoomService", b =>
                {
                    b.HasOne("IlliaUlianych_APB_TZ.Entities.RoomService", null)
                        .WithMany()
                        .HasForeignKey("AvailableServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IlliaUlianych_APB_TZ.Entities.ConferenceRoom", null)
                        .WithMany()
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IlliaUlianych_APB_TZ.Entities.Booking", b =>
                {
                    b.HasOne("IlliaUlianych_APB_TZ.Entities.ConferenceRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
